version: '2'

tasks:
  build:
    needs: [clean]
    cmds:
      - riscv64-unknown-elf-gcc -O0 -Wall -Wextra -c -mcmodel=medany kernel.c -o kernel.o -ffreestanding
      - riscv64-unknown-elf-gcc -O0 -c entry.S -o entry.o
      - riscv64-unknown-elf-ld -O0 -T linker.ld -nostdlib kernel.o entry.o -o kernel.elf
  boot:
    cmds:
      - qemu-system-riscv64 -machine virt -bios none -kernel kernel.elf -serial mon:stdio
  clean:
    cmds:
      - rm -f entry.o kernel.o kernel.elf riscv64-virt.dtb riscv64-virt.dts
  generate-device-tree:
    cmds:
      - qemu-system-riscv64 -machine virt -machine dumpdtb=riscv64-virt.dtb
      - dtc -I dtb -O dts -o riscv64-virt.dts riscv64-virt.dtb
      - rm -f riscv64-virt.dtb
