version: '2'

tasks:
  build:
    needs: [clean]
    cmds:
      - riscv64-unknown-elf-gcc -O0 -Wall -Wextra -c -mcmodel=medany *.c -o kernel.o -ffreestanding
      - riscv64-unknown-elf-gcc -O0 -c entry.S -o entry.o
      - riscv64-unknown-elf-ld -O0 -T linker.ld -nostdlib kernel.o entry.o -o kernel.elf
  build-fedora:
    needs: [clean]
    cmds:
      - |
       for file in $(ls \*.c); do
         module=${file%.*}
         riscv64-linux-gnu-gcc -O0 {{.BUILD_FLAGS|default ""}} -Wall -Wextra -c -mcmodel=medany $module.c -o $module.o -ffreestanding
       done
      - riscv64-linux-gnu-gcc -O0 -c entry.S -o entry.o
      - riscv64-linux-gnu-ld -O0 -T linker.ld -nostdlib *.o -o kernel.elf
  build-johannes:
    needs: [clean]
    cmds:
      - task build-fedora
  build-raphael:
    needs: [clean]
    cmds:
      - task build-fedora
    env:
      BUILD_FLAGS: "-DBIG_HEX"
  boot:
    cmds:
      - qemu-system-riscv64 -machine virt -bios none -kernel kernel.elf -serial mon:stdio
  clean:
    cmds:
      - rm -f *.o kernel.elf riscv64-virt.dtb riscv64-virt.dts
  generate-device-tree:
    cmds:
      - qemu-system-riscv64 -machine virt -machine dumpdtb=riscv64-virt.dtb
      - dtc -I dtb -O dts -o riscv64-virt.dts riscv64-virt.dtb
      - rm -f riscv64-virt.dtb
